CREATE TABLE game (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

   invitation SMALLINT NOT NULL,
   type SMALLINT NOT NULL,
   ai_type SMALLINT NOT NULL,
   status SMALLINT NOT NULL,

   started_at TIMESTAMP WITHOUT TIME ZONE,
   last_move_at TIMESTAMP WITHOUT TIME ZONE,

   current_state VARCHAR(255) NOT NULL,
   non_capture_moves INTEGER,

   user_starts BOOLEAN NOT NULL,
   user_turn BOOLEAN NOT NULL,

   user_id BIGINT NOT NUll,
   opponent_id BIGINT,
   CONSTRAINT pk_game PRIMARY KEY (id),
   CONSTRAINT fk_user_id
      FOREIGN KEY(user_id)
      REFERENCES account(id),
   CONSTRAINT fk_opponent_id
      FOREIGN KEY(opponent_id)
      REFERENCES account(id)
);

CREATE TABLE move (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   current_state VARCHAR(255),
   move VARCHAR(255),
   timestamp TIMESTAMP WITHOUT TIME ZONE,
   game_id BIGINT NOT NULL,
   user_id BIGINT,
   CONSTRAINT pk_move PRIMARY KEY (id),
   CONSTRAINT fk_game_id
      FOREIGN KEY(game_id)
      REFERENCES game(id),
   CONSTRAINT fk_user_id
      FOREIGN KEY(user_id)
      REFERENCES account(id)
);